import { BlogPost } from "@/types/blog.types";

export const blogPosts: BlogPost[] = [
  {
    _id: "1",
    title: "كيف تبني خطة عمل ناجحة لمشروعك الناشئ في 2024",
    summary:
      "دليل شامل لرواد الأعمال لبناء خطة عمل محكمة تضمن نجاح مشروعهم في السوق العربي مع مراعاة متغيرات السوق الحالية",
    content: [
      {
        type: "paragraph",
        content: "في عالم ريادة الأعمال المتسارع، أصبح من الضروري وضع خطة عمل محكمة تضمن نجاح مشروعك...",
      },
      { type: "heading", content: "العناصر الأساسية لخطة العمل" },
      { type: "list", content: ["دراسة السوق المستهدف", "تحليل المنافسين", "الخطة المالية", "استراتيجية التسويق"] },
    ],
    image: "https://images.unsplash.com/photo-1487528278747-ba99ed528ebc?w=800",
    createdAt: "2024-03-01",
    readTime: 8,
    category: "ريادة الأعمال",
    author: {
      name: "أحمد محمد",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
      role: "مستشار ريادة أعمال",
    },
    tags: ["خطة عمل", "ريادة أعمال", "مشاريع ناشئة"],
  },
  {
    _id: "2",
    title: "التسويق الرقمي في عصر الذكاء الاصطناعي",
    summary: "كيف يمكن للشركات الناشئة الاستفادة من تقنيات الذكاء الاصطناعي في حملاتها التسويقية وزيادة عائد الاستثمار",
    content: [],
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800",
    createdAt: "2024-03-05",
    readTime: 6,
    category: "التسويق",
    author: {
      name: "سارة أحمد",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      role: "خبيرة تسويق رقمي",
    },
    tags: ["تسويق رقمي", "ذكاء اصطناعي", "تسويق"],
  },
  {
    _id: "3",
    title: "مستقبل التجارة الإلكترونية في العالم العربي",
    summary: "نظرة تحليلية على مستقبل التجارة الإلكترونية في المنطقة العربية والفرص المتاحة للشركات الناشئة",
    content: [],
    image: "https://images.unsplash.com/photo-1416339684178-3a239570f315?w=800",
    createdAt: "2024-03-08",
    readTime: 10,
    category: "تجارة إلكترونية",
    author: {
      name: "محمد علي",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
      role: "خبير تجارة إلكترونية",
    },
    tags: ["تجارة إلكترونية", "تكنولوجيا", "مبيعات"],
  },
  {
    _id: "4",
    title: "استراتيجيات التمويل للشركات الناشئة",
    summary: "دليل شامل حول مصادر التمويل المختلفة المتاحة للشركات الناشئة في العالم العربي",
    content: [],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800",
    createdAt: "2024-03-10",
    readTime: 7,
    category: "التمويل",
    author: {
      name: "ريم خالد",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
      role: "مستشارة تمويل",
    },
    tags: ["تمويل", "استثمار", "شركات ناشئة"],
  },
  {
    _id: "5",
    title: "بناء فريق عمل ناجح لمشروعك الناشئ",
    summary: "كيفية اختيار وإدارة فريق عمل متميز يساهم في نجاح مشروعك الناشئ",
    content: [],
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800",
    createdAt: "2024-03-12",
    readTime: 5,
    category: "إدارة",
    author: {
      name: "عمر يوسف",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      role: "مدير موارد بشرية",
    },
    tags: ["إدارة", "موارد بشرية", "قيادة"],
  },
  {
    _id: "6",
    title: "تحديات وحلول في عالم الشركات الناشئة",
    summary: "استعراض لأبرز التحديات التي تواجه الشركات الناشئة وحلول عملية للتغلب عليها",
    content: [],
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
    createdAt: "2024-03-15",
    readTime: 9,
    category: "ريادة الأعمال",
    author: {
      name: "لينا سعيد",
      avatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100",
      role: "مستشارة أعمال",
    },
    tags: ["تحديات", "حلول", "شركات ناشئة"],
  },
  {
    _id: "7",
    title: "الابتكار في نماذج الأعمال التجارية",
    summary: "كيف يمكن للشركات الناشئة ابتكار نماذج أعمال جديدة تلبي احتياجات السوق المتغيرة",
    content: [],
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800",
    createdAt: "2024-03-18",
    readTime: 6,
    category: "ابتكار",
    author: {
      name: "فهد العمري",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
      role: "مستشار ابتكار",
    },
    tags: ["ابتكار", "نماذج أعمال", "تطوير"],
  },
  {
    _id: "8",
    title: "التحول الرقمي للشركات التقليدية",
    summary: "دليل عملي لمساعدة الشركات التقليدية في رحلة التحول الرقمي وتبني التكنولوجيا الحديثة",
    content: [],
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800",
    createdAt: "2024-03-20",
    readTime: 8,
    category: "تكنولوجيا",
    author: {
      name: "طارق النجار",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
      role: "خبير تحول رقمي",
    },
    tags: ["تحول رقمي", "تكنولوجيا", "تطوير أعمال"],
  },
  {
    _id: "9",
    title: "استراتيجيات النمو السريع للشركات الناشئة",
    summary: "كيفية تحقيق النمو السريع للشركات الناشئة مع الحفاظ على الاستدامة",
    content: [],
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800",
    createdAt: "2024-03-22",
    readTime: 7,
    category: "نمو",
    author: {
      name: "نورا الحسن",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      role: "مستشارة نمو",
    },
    tags: ["نمو", "استراتيجية", "تطوير"],
  },
  {
    _id: "10",
    title: "مستقبل العمل عن بعد وأثره على الشركات الناشئة",
    summary: "تحليل شامل لتأثير العمل عن بعد على مستقبل الشركات الناشئة وكيفية الاستفادة منه",
    content: [],
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800",
    createdAt: "2024-03-25",
    readTime: 5,
    category: "إدارة",
    author: {
      name: "سامي الخالد",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      role: "خبير إدارة عن بعد",
    },
    tags: ["عمل عن بعد", "إدارة", "مستقبل العمل"],
  },
];
